name = "HalfSpaceTrees"
uuid = "8a4a2dd9-6b83-4636-a23b-cd6412e84079"
authors = ["Eric Matti and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
